Constants = {
    SPAWN_AREA_SIZE: 10,

    TERRAIN_WALL: 'wall',

    ENTITY_BULLET: 'bullet',

    ORIENTATION_VERTICAL: 0,
    ORIENTATION_HORIZONTAL: 1,

    BOUNCE_NO: 0,
    BOUNCE_HORIZONTAL: 1,
    BOUNCE_VERTICAL: 2,
    BOUNCE_BOTH: 3,

    COLLIDING_HORIZONTAL_SIDE: 1,
    COLLIDING_VERTICAL_SIDE: 2,

    ACTION_SHOOT: 'shoot',
    ACTION_MOVE: 'move',

    PLAYER_SIZE: 8,
    MOVE_MAX_DISTANCE: 20,
    WALL_WIDTH: 10,

    BULLET_SIZE: 2,
    BULLET_SPEED: 1,
    BULLET_LIFETIME: 50000, //in milliseconds

    OK: 0,
    ERR_SUCCEEDED: 1, //it be like that sometimes
    ERR_INVALID_ARGUMENTS: 2,
    ERR_ILLEGAL: 3
};